name: build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - name: Installation
        run: yarn
      - name: Build
        run: yarn workspace website build --locale en
