name: Publish User Guide

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.1
      - run: yarn
      - run: yarn build
      - run: git config --global user.email "Mohab.MohieElDeen@outlook.com"
      - run: git config --global user.name "Mohab Mohie"
      - run: GIT_USER=MohabMohie yarn deploy
