name: Publish User Guide

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: cd apidocs
      - run: npm run build
      - run: GIT_USER=MohabMohie yarn deploy
