name: Publish User Guide

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          token: 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
          node-version: 12
      - run: yarn
      - run: yarn build
      - run: GIT_USER=MohabMohie yarn deploy
