name: documentation

on: [push]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      #- uses: webfactory/ssh-agent@v0.5.2
      #  with:
      #    ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      #- name: Install SSH Key
      #  uses: shimataro/ssh-key-action@v2.3.0
      #  with:
      #    key: ${{secrets.GH_PAGES_DEPLOY}}
      #    known_hosts: '140.82.113.3'
      - name: Release to GitHub Pages
        env:
          USE_SSH: false
          GIT_USER: MohabMohie
          GIT_PASS: ${{secrets.PERSONAL_TOKEN}}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run deploy
